version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: '${APP_NAME}_mysql'
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=${DEV_DB_PASSWORD}
      - MYSQL_DATABASE=${DEV_DB_DATABASE}
    ports:
      - '${DEV_DB_PORT:-3306}:3306'
    networks:
      - node
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: '${APP_NAME}_node_app'
    restart: unless-stopped
    ports:
      - '${APP_PORT:-8000}:${APP_PORT:-8000}'
    depends_on:
      - mysql
    volumes:
      - '.:/var/www/html'
    networks:
      - node
  localtunnel:
    image: efrecon/localtunnel
    restart: on-failure
    command:
      --local-host app --port ${APP_PORT:-8000} --subdomain ${LOCALTUNNEL_SUBDOMAIN}
    links:
      - app
    depends_on:
      - app
    networks:
      - node
networks:
  node:
    driver: bridge